CREATE OR REPLACE TRANSIENT DATABASE TASK_DB;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID INT AUTOINCREMENT START = 1 INCREMENT =1,
    FIRST_NAME VARCHAR(40) DEFAULT 'JENNIFER' ,
    CREATE_DATE DATE);

SHOW tasks; 

CREATE OR REPLACE TASK "test_task"
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = '1 MINUTE'
AS
INSERT INTO CUSTOMERS(CREATE_DATE) VALUES(CURRENT_DATE); 

ALTER TASK "test_task" RESUME; 


SELECT * FROM customers; 
ALTER TASK "test_task" SUSPEND; 


-- cronjob tasks.

CREATE OR REPLACE TASK "TEST_TASK_CRON"
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON * * * * * EST'
AS
INSERT INTO CUSTOMERS(CREATE_DATE) VALUES(CURRENT_DATE); 

SHOW TASKS; 
ALTER TASK "TEST_TASK_CRON" RESUME; 

SELECT * FROM customers; 
ALTER TASK "TEST_TASK_CRON" suspend; 


-- 