-- Create a materialized view called PARTS in the database DEMO_DB from the following statement:

-- SELECT 
-- AVG(PS_SUPPLYCOST) as PS_SUPPLYCOST_AVG,
-- AVG(PS_AVAILQTY) as PS_AVAILQTY_AVG,
-- MAX(PS_COMMENT) as PS_COMMENT_MAX
-- FROM"SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."PARTSUPP"
--Execute the SELECT before creating the materialized view and note down the time until the query is executed.

SELECT 
AVG(PS_SUPPLYCOST) as PS_SUPPLYCOST_AVG,
AVG(PS_AVAILQTY) as PS_AVAILQTY_AVG,
MAX(PS_COMMENT) as PS_COMMENT_MAX
FROM"SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."PARTSUPP"
-- TAKES ABOUT 11s to execute

CREATE OR REPLACE MATERIALIZED VIEW ASSIGNMENT13_MATERIALIZED_VIEW
AS
SELECT 
AVG(PS_SUPPLYCOST) as PS_SUPPLYCOST_AVG,
AVG(PS_AVAILQTY) as PS_AVAILQTY_AVG,
MAX(PS_COMMENT) as PS_COMMENT_MAX
FROM"SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."PARTSUPP";

SELECT * FROM OUR_FIRST_DB.PUBLIC.ASSIGNMENT13_MATERIALIZED_VIEW;
-- TAKES ABOUT 248ms


show tasks; 

