-- We have several roles
-- ACCOUNTADMIN
-- SECURITYADMIN
-- USERADMIN
-- SYSADMIN
-- PUBLIC 

-- Let's create three users
CREATE OR REPLACE USER Adam
PASSWORD = '******'
LOGIN_NAME = 'ADAM'
DEFAULT_ROLE = ACCOUNTADMIN
MUST_CHANGE_PASSWORD = true; 

GRANT ROLE ACCOUNTADMIN to USER Adam; 

CREATE OR REPLACE USER Bart
PASSWORD = '********'
LOGIN_NAME = 'BART'
DEFAULT_ROLE = SECURITYADMIN
MUST_CHANGE_PASSWORD = true;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SECURITYADMIN; 

GRANT ROLE ACCOUNTADMIN to USER Bart; 

CREATE OR REPLACE USER Cynthia
PASSWORD = '***********'
LOGIN_NAME = 'CYNTHIA'
DEFAULT_ROLE = SYSADMIN
MUST_CHANGE_PASSWORD = true;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN; 

GRANT ROLE ACCOUNTADMIN to USER Cynthia; 

SHOW users; 